name: Deploy Cloudflare Worker

on:
  push:
    branches: [ main ]      # deploy staging on every push to main
    tags: [ 'v*' ]          # deploy production when you push a tag like v1.0.0
  workflow_dispatch:         # allow manual runs

concurrency:
  group: deploy-worker
  cancel-in-progress: true

jobs:
  deploy-staging:
    if: startsWith(github.ref, 'refs/heads/main')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/worker
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm ci
      - name: Deploy to STAGING
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: npx wrangler deploy --env=staging

  deploy-production:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/worker
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm ci
      - name: Deploy to PRODUCTION
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: npx wrangler deploy --env=production
